#!/usr/bin/env bash
# Create a new configuration file for nginx
/etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }
}
