#!/usr/bin/env bash

STUDENT_ID="Fatumayattani"

# Install HAproxy
sudo apt update
sudo apt install -y haproxy

# Configure HAproxy to send traffic to web-01 and web-02
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server ${Fatumayattani-web-01 ${Fatumayattani-web-01:80 check
    server ${Fatumayattani}-web-02 ${Fatumayattani}-web-02:80 check
EOF

# Restart HAproxy
sudo systemctl restart haproxy

# Enable HAproxy init script
sudo systemctl enable haproxy
