#!/usr/bin/env bash
#update the package list
#nginx configuration file to listen on all active IPv4 IPs
#verify that nginx is listening on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
